language: node_js
node_js: 
  - node
stages: 
  - docker_build
  - deploy 
before_install: 
  - "openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out travis_rsa -d"
branch: 
  only: 
    - main
install: 
  - "npm install"
  - "docker --version"
jobs: 
  include: 
    - 
      name: "Build docker container"
      script: 
        - "echo \"BUILD\""
        - "docker build -t minitwit_fe ."
      stage: docker_build
    - 
      install: skip
      name: "Deploy on DO"
      script: "ssh -o \"StrictHostKeyChecking no\" ${MT_USER}@${MT_SERVER} \\\n\
          \"docker stop minitwit_fe && \\\n\
          docker rm minitwit_fe && \\\n\
          docker run -it -p 8080:80 -d --name minitwit_fe minitwit_fe\" \n"
      stage: deploy

